
// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      admin_notes: {
        Row: {
          admin_id: string | null
          created_at: string | null
          id: string
          note: string
          user_id: string | null
        }
        Insert: {
          admin_id?: string | null
          created_at?: string | null
          id?: string
          note: string
          user_id?: string | null
        }
        Update: {
          admin_id?: string | null
          created_at?: string | null
          id?: string
          note?: string
          user_id?: string | null
        }
        Relationships: []
      }
      bookings: {
        Row: {
          accepted_at: string | null
          chain: string | null
          client_id: string | null
          created_at: string | null
          creator_id: string | null
          delivered_at: string | null
          id: string
          payment_address: string | null
          release_at: string | null
          service_id: string | null
          status: string | null
          tx_hash: string | null
          updated_at: string | null
          usdc_amount: number
        }
        Insert: {
          accepted_at?: string | null
          chain?: string | null
          client_id?: string | null
          created_at?: string | null
          creator_id?: string | null
          delivered_at?: string | null
          id?: string
          payment_address?: string | null
          release_at?: string | null
          service_id?: string | null
          status?: string | null
          tx_hash?: string | null
          updated_at?: string | null
          usdc_amount: number
        }
        Update: {
          accepted_at?: string | null
          chain?: string | null
          client_id?: string | null
          created_at?: string | null
          creator_id?: string | null
          delivered_at?: string | null
          id?: string
          payment_address?: string | null
          release_at?: string | null
          service_id?: string | null
          status?: string | null
          tx_hash?: string | null
          updated_at?: string | null
          usdc_amount?: number
        }
        Relationships: []
      }
      contact_messages: {
        Row: {
          created_at: string | null
          email: string
          id: string
          message: string
          name: string
          status: string | null
          subject: string
        }
        Insert: {
          created_at?: string | null
          email: string
          id?: string
          message: string
          name: string
          status?: string | null
          subject: string
        }
        Update: {
          created_at?: string | null
          email?: string
          id?: string
          message?: string
          name?: string
          status?: string | null
          subject?: string
        }
        Relationships: []
      }
      creators: {
        Row: {
          approved: boolean | null
          approved_at: string | null
          category: string | null
          created_at: string | null
          headline: string | null
          id: string
          intro_video_url: string | null
          payout_address_eth: string | null
          payout_address_sol: string | null
          payout_address_bsc: string | null
          payout_address_sui: string | null
          payout_address_cardano: string | null
          priority_score: number | null
          rating: number | null
          review_count: number | null
          tier: string | null
          user_id: string | null
        }
        Insert: {
          approved?: boolean | null
          approved_at?: string | null
          category?: string | null
          created_at?: string | null
          headline?: string | null
          id?: string
          intro_video_url?: string | null
          payout_address_eth?: string | null
          payout_address_sol?: string | null
          payout_address_bsc?: string | null
          payout_address_sui?: string | null
          payout_address_cardano?: string | null
          priority_score?: number | null
          rating?: number | null
          review_count?: number | null
          tier?: string | null
          user_id?: string | null
        }
        Update: {
          approved?: boolean | null
          approved_at?: string | null
          category?: string | null
          created_at?: string | null
          headline?: string | null
          id?: string
          intro_video_url?: string | null
          payout_address_eth?: string | null
          payout_address_sol?: string | null
          payout_address_bsc?: string | null
          payout_address_sui?: string | null
          payout_address_cardano?: string | null
          priority_score?: number | null
          rating?: number | null
          review_count?: number | null
          tier?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      direct_messages: {
        Row: {
          body: string
          created_at: string
          from_user_id: string
          id: string
          to_user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          from_user_id: string
          id?: string
          to_user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          from_user_id?: string
          id?: string
          to_user_id?: string
        }
        Relationships: []
      }
      disputes: {
        Row: {
          booking_id: string | null
          created_at: string | null
          id: string
          opened_by: string
          reason: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          status: string | null
        }
        Insert: {
          booking_id?: string | null
          created_at?: string | null
          id?: string
          opened_by: string
          reason: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string | null
        }
        Update: {
          booking_id?: string | null
          created_at?: string | null
          id?: string
          opened_by?: string
          reason?: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string | null
        }
        Relationships: []
      }
      messages: {
        Row: {
          attachments: Json | null
          body: string
          booking_id: string | null
          created_at: string | null
          from_user_id: string | null
          id: string
          to_user_id: string | null
        }
        Insert: {
          attachments?: Json | null
          body: string
          booking_id?: string | null
          created_at?: string | null
          from_user_id?: string | null
          id?: string
          to_user_id?: string | null
        }
        Update: {
          attachments?: Json | null
          body?: string
          booking_id?: string | null
          created_at?: string | null
          from_user_id?: string | null
          id?: string
          to_user_id?: string | null
        }
        Relationships: []
      }
      payments: {
        Row: {
          admin_wallet_address: string
          amount: number
          booking_id: string | null
          created_at: string | null
          creator_id: string | null
          currency: string
          id: string
          network: string
          payment_type: 'service_booking' | 'creator_tier'
          service_id: string | null
          status: 'pending' | 'verified' | 'rejected'
          tx_hash: string
          updated_at: string | null
          user_id: string
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          admin_wallet_address: string
          amount: number
          booking_id?: string | null
          created_at?: string | null
          creator_id?: string | null
          currency: string
          id?: string
          network: string
          payment_type: 'service_booking' | 'creator_tier'
          service_id?: string | null
          status?: 'pending' | 'verified' | 'rejected'
          tx_hash: string
          updated_at?: string | null
          user_id: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          admin_wallet_address?: string
          amount?: number
          booking_id?: string | null
          created_at?: string | null
          creator_id?: string | null
          currency?: string
          id?: string
          network?: string
          payment_type?: 'service_booking' | 'creator_tier'
          service_id?: string | null
          status?: 'pending' | 'verified' | 'rejected'
          tx_hash?: string
          updated_at?: string | null
          user_id?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: []
      }
      pricing_tiers: {
        Row: {
          active: boolean
          created_at: string
          display_name: string
          features: Json
          id: string
          price_usdc: number
          tier_name: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          display_name: string
          features?: Json
          id?: string
          price_usdc?: number
          tier_name: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          display_name?: string
          features?: Json
          id?: string
          price_usdc?: number
          tier_name?: string
          updated_at?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          booking_id: string | null
          comment: string | null
          created_at: string | null
          id: string
          rating: number | null
          reviewee_id: string | null
          reviewer_id: string | null
        }
        Insert: {
          booking_id?: string | null
          comment?: string | null
          created_at?: string | null
          id?: string
          rating?: number | null
          reviewee_id?: string | null
          reviewer_id?: string | null
        }
        Update: {
          booking_id?: string | null
          comment?: string | null
          created_at?: string | null
          id?: string
          rating?: number | null
          reviewee_id?: string | null
          reviewer_id?: string | null
        }
        Relationships: []
      }
      services: {
        Row: {
          active: boolean | null
          category: string | null
          created_at: string | null
          creator_id: string | null
          delivery_days: number | null
          description: string | null
          id: string
          payment_method: string | null
          price_usdc: number | null
          title: string
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          category?: string | null
          created_at?: string | null
          creator_id?: string | null
          delivery_days?: number | null
          description?: string | null
          id?: string
          payment_method?: string | null
          price_usdc?: number | null
          title: string
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          category?: string | null
          created_at?: string | null
          creator_id?: string | null
          delivery_days?: number | null
          description?: string | null
          id?: string
          payment_method?: string | null
          price_usdc?: number | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      shopping_cart: {
        Row: {
          added_at: string | null
          creator_id: string
          id: string
          service_id: string
          user_id: string
        }
        Insert: {
          added_at?: string | null
          creator_id: string
          id?: string
          service_id: string
          user_id: string
        }
        Update: {
          added_at?: string | null
          creator_id?: string
          id?: string
          service_id?: string
          user_id?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string | null
          email: string | null
          handle: string | null
          id: string
          portfolio_url: string | null
          payout_address_bsc: string | null
          payout_address_cardano: string | null
          payout_address_sui: string | null
          referral_code: string | null
          referral_credits: number | null
          referred_by: string | null
          role: string | null
          social_links: Json | null
          updated_at: string | null
          website_url: string | null
          youtube_url: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          email?: string | null
          handle?: string | null
          id: string
          portfolio_url?: string | null
          payout_address_bsc?: string | null
          payout_address_cardano?: string | null
          payout_address_sui?: string | null
          referral_code?: string | null
          referral_credits?: number | null
          referred_by?: string | null
          role?: string | null
          social_links?: Json | null
          updated_at?: string | null
          website_url?: string | null
          youtube_url?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          email?: string | null
          handle?: string | null
          id?: string
          portfolio_url?: string | null
          payout_address_bsc?: string | null
          payout_address_cardano?: string | null
          payout_address_sui?: string | null
          referral_code?: string | null
          referral_credits?: number | null
          referred_by?: string | null
          role?: string | null
          social_links?: Json | null
          updated_at?: string | null
          website_url?: string | null
          youtube_url?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database["public"]["Tables"] & Database["public"]["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database["public"]["Tables"] &
        Database["public"]["Views"])
    ? (Database["public"]["Tables"] &
        Database["public"]["Views"])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
    ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
    ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof Database["public"]["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof Database["public"]["Enums"]
    ? Database["public"]["Enums"][PublicEnumNameOrOptions]
    : never
