// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpxqkiajkkeizsewhoel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNweHFraWFqa2tlaXpzZXdob2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTUxMDMsImV4cCI6MjA3MTEzMTEwM30.3DLJ7DUDc_X-SIQp1AEE4ilw7YpVdr_MF5V0xRFnOxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});